# exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once = systemctl --user start graphical-session.target
exec-once = vicinae server
exec-once = systemctl --user restart xdg-desktop-portal.service --ignore-dependencies
# exec-once = ollama serve
exec-once = ydotoold
exec-once = kanata
exec-once = ssh-add
exec-once = noctalia -d
exec-once = kitty --app-id=kitty-session --session ~/.config/kitty/default.kitty-session
# exec-once = brave

blur = 1
blur_layer = 1
circle_layout = scroller,fair
cursor_hide_timeout = 2
drag_lock = 0
drag_tile_to_tile = 1
focus_cross_tag = 1
focus_on_activate = 1
focused_opacity = 1.0
jump_labels = 123456789
layer_shadows = 0
no_border_when_single = 1
numlockon = 1
ov_tab_mode = 1
shadows = 0
single_scratchpad = 0
sloppyfocus = 0
trackpad_accel_speed = 0.25
trackpad_natural_scrolling = 1
unfocused_opacity = 1.0
view_current_to_back = 1

# appearance
borderpx = 1
border_radius = 12
# bordercolor = 0x90909aff
focuscolor = 0x29B6F6FF
gappih = 10

# keyboard
xkb_rules_layout = us
# xkb_rules_options = caps:hyper

# cursor
# cursor_theme = catppuccin-mocha-lavender-cursors

# animations
animations = 1
animation_type_open = zoom
animation_type_close = zoom
layer_animations = 0
layer_animation_type_open = zoom
layer_animation_type_close = zoom
animation_duration_move = 300
animation_duration_open = 300
animation_duration_tag = 200
animation_duration_close = 300
tag_animation_direction = 0

# scroller layout setting
scroller_structs = 5
scroller_default_proportion = 0.5
scroller_default_proportion_single = 1.0
# scroller_prefer_center = 1
scroller_prefer_overspread = 1
scroller_proportion_preset = 0.25,0.5,0.75,1.0

# Imports
source = ~/.config/mango/binds.conf
source = ~/.config/mango/rules.conf

# This sources the shell theme & binds
source = /home/kev/.config/mango/noctalia/noctalia-v5-binds.conf
# source = /home/kev/.config/mango/dms/dms-binds.conf
# source = /home/kev/.config/mango/dms/colors.conf
# source = /home/kev/.config/mango/dms/cursor.conf
