monitorrule=make:Dell Inc.,model:DELL S2722DGM,width:2560,height:1440,refresh:165.080002,x:0,y:0
windowrule=appid:firefox,scroller_proportion:1.0
windowrule=appid:firefox,focused_opacity:1.0
windowrule=appid:firefox,unfocused_opacity:1.0
windowrule=appid:zen,scroller_proportion:1.0
windowrule=appid:zen,focused_opacity:1.0
windowrule=appid:zen,unfocused_opacity:1.0
windowrule=title:satty,focused_opacity:1.0
windowrule=appid:kitty,scroller_proportion:0.5
windowrule=isfloating:1,width:420,height:240,offsetx:-100,offsety:20,title:Picture-in-Picture
windowrule=isfloating:1,width:2000,height:1000,appid:floater
# windowrule=width:355,height:190,offsetx:0,offsety:0,isoverlay:1,isglobal:0,appid:Chromium-browser
windowrule=isfloating:1,width:1000,height:1000,appid:com.gabm.satty
windowrule=isfloating:1,width:700,height:450,appid:remind_tui
# windowrule=isnamedscratchpad:1,width:2000,height:1200,appid:Spotify
windowrule=isnamedscratchpad:1,width:2400,height:1370,appid:kitty-session
windowrule=isnamedscratchpad:1,width:600,height:300,appid:qalculate-gtk
# windowrule=force_maximize:0,appid:.*

layerrule=noanim:1,layer_name:selection
layerrule=noanim:1,layer_name:dms:.*

tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
