monitorrule=make:Dell Inc.,model:DELL S2722DGM,width:2560,height:1440,refresh:165.080002,x:0,y:0
windowrule=		appid:firefox,				scroller_proportion:1.0
windowrule=		appid:firefox,				focused_opacity:1.0
windowrule=		appid:firefox,				unfocused_opacity:1.0
windowrule=		appid:zen,	    			scroller_proportion:1.0
windowrule=		appid:zen,	    			focused_opacity:1.0
windowrule=		appid:zen,	    			unfocused_opacity:1.0
windowrule=  	title:satty,        		focused_opacity:1.0
windowrule=  	appid:kitty,        		scroller_proportion:0.5
windowrule=  	title:Picture-in-Picture,   isfloating:1, width:420, height:240, offsetx:-100, offsety:20
windowrule=  	appid:floater,          	isfloating:1, width:2000,height:1000
windowrule=  	appid:com.danklinux.dms,	isfloating:1, width:800,height:1300
windowrule=  	appid:com.gabm.satty,   	isfloating:1, width:1000, height:1000
windowrule=  	appid:remind_tui,       	isfloating:1, width:700, height:450
windowrule=  	appid:kitty-session,    	isnamedscratchpad:1, width:2400, height:1370
windowrule=  	appid:qalculate-gtk,    	isnamedscratchpad:1, width:600, height:300
# windowrule=	appid:.*,					force_maximize:0   		

layerrule=		layer_name:selection, 		noanim:1
layerrule=		layer_name:dms:.*,    		noanim:1
layerrule=		layer_name:noctalia.*,		noanim:1

tagrule=		id:1,						layout_name:scroller
tagrule=		id:2,						layout_name:scroller
tagrule=		id:3,						layout_name:scroller
tagrule=		id:4,						layout_name:scroller
