# Theming
font: VictorMono Nerd Font 16
background: "#192330"
color: "#fbf1c7"
border: "#96883e"
separator: " ➜ "
border_width: 1
corner_r: 0
padding: 15 # Defaults to corner_r

# Anchor and margin
anchor: center # One of center, left, rght, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor s not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

menu:
  - key: "a"
    desc: ai
    submenu:
    - key: "a"
      desc: aichat
      cmd: kitty aichat -m llama-cpp:lfm2-8b -r concise -s session --empty-session
    - key: "1"
      desc: LFM2-8B-A1B (fast and concise)
      cmd: notify-send -u low 'AI Model' 'Loading LFM2'; pkill llama-server; niri msg action spawn-sh -- "llama-server -a 'LFM2-8B-A1B' -m ~/Code/models/LFM2-8B-A1B-Q4_K_M.gguf --temp 0.3 --min-p 0.15 --repeat-penalty 1.05 --port 8081 --host 127.0.0.1"
    - key: "2"
      desc: Qwen3-4B-Instruct (fast and friendly)
      cmd: notify-send -u low 'AI Model' 'Loading Qwen3-4B-Instruct'; pkill llama-server; niri msg action spawn-sh -- "llama-server -a 'Qwen3-4B-Instruct' -m ~/Code/models/Qwen3-4B-Instruct-2507-IQ4_XS.gguf --temp 0.7 --top-p 0.8 --top-k 20 --min-p 0 --presence-penalty 1.05 --port 8081 --host 127.0.0.1"
    - key: "3"
      desc: Qwen3-30B-A3B (MoE)
      cmd: notify-send -u low 'AI Model' 'Loading Qwen3-30B-A3B'; pkill llama-server; niri msg action spawn-sh -- "llama-server -a 'Qwen-30b-A3B' -m ~/Code/models/Qwen3-30B-A3B-Instruct-2507-Q4_K_M.gguf --temp 0.7 --top-p 0.8 --min-p 0 --top-k 20 --presence-penalty 1.05 --port 8081 --host 127.0.0.1"
    - key: "4"
      desc: GPT-OSS-20b (thinking)
      cmd: notify-send -u low 'AI Model' 'Loading GPT-OSS-20B'; pkill llama-server; niri msg action spawn-sh -- "llama-server -a 'GPT-OSS-20b' -m ~/Code/models/gpt-oss-20b-MXFP4.gguf --jinja --ctx-size 0 -ub 2048 -b 2048 --n-cpu-moe 21 --temp 1.0 --top-p 1.0 --top-k 0 --min-p 0 --port 8081 --host 127.0.0.1"
  - key: "c"
    desc: configs
    submenu:
      - key: "d"
        desc: toggle dark mode
        cmd: darkman toggle
      - key: "h"
        desc: helix
        submenu:
          - key: "c"
            desc: config
            cmd: kitty hx ~/.config/helix/config.toml
          - key: "l"
            desc: languages
            cmd: kitty hx ~/.config/helix/languages.toml
          - key: "e"
            desc: expansions
            cmd: kitty yazi ~/.config/helix/snippets
      - key: "n"
        desc: nixos
        submenu:
          - key: "u"
            desc: users
            cmd: kitty hx ~/NixOS/modules/users.nix
          - key: "e"
            desc: environment
            cmd: kitty hx ~/NixOS/modules/environment.nix
          - key: "p"
            desc: programs
            cmd: kitty hx ~/NixOS/modules/programs.nix
          - key: "s"
            desc: services
            cmd: kitty hx ~/NixOS/modules/services.nix
          - key: "f"
            desc: flake
            cmd: kitty hx ~/NixOS/flake.nix
          - key: "h"
            desc: home
            cmd: kitty hx ~/NixOS/home/home.nix
      - key: "c"
        desc: which-key menus
        cmd: kitty hx ~/.config/wlr-which-key/config.yaml
      - key: "N"
        desc: niri
        submenu:
          - key: "b"
            desc: binds
            cmd: kitty hx ~/.config/niri/binds.kdl
          - key: "e"
            desc: environment
            cmd: kitty hx ~/.config/niri/environment.kdl
          - key: "i"
            desc: input
            cmd: kitty hx ~/.config/niri/input.kdl
          - key: "l"
            desc: layer-rules
            cmd: kitty hx ~/.config/niri/layer-rules.kdl
          - key: "L"
            desc: layout
            cmd: kitty hx ~/.config/niri/layout.kdl
          - key: "o"
            desc: output
            cmd: kitty hx ~/.config/niri/output.kdl
          - key: "s"
            desc: spawns
            cmd: kitty hx ~/.config/niri/spawns.kdl
          - key: "t"
            desc: top-level (config.kdl)
            cmd: kitty hx ~/.config/niri/config.kdl
          - key: "w"
            desc: window-rules
            cmd: kitty hx ~/.config/niri/window-rules.kdl
      - key: "p"
        desc: color picker
        cmd: niri-pick-color
  - key: "d"
    desc: dms
    submenu:
    - key: "k"
      desc: kill shell
      cmd: dms kill
    - key: "l"
      desc: launch shell
      cmd: dms run
    - key: "r"
      desc: restart shell
      cmd: dms restart
    - key: "s"
      desc: open settings
      cmd: dms ipc settings toggle
    - key: "t"
      desc: toggle dark/light theme
      cmd: dms ipc theme toggle
    - key: "w"
      desc: wallpaper
      submenu:
        - key: "n"
          desc: next wallpaper
          cmd: dms ipc wallpaper next
        - key: "p"
          desc: previous wallpaper
          cmd: dms ipc wallaper prev
  - key: "f"
    desc: file manager
    cmd: nautilus
  - key: "j"
    desc: jj repos
    submenu:
      - key: "1"
        desc: nixos
        cmd: kitty  --app-id repo --title=nixos -e jjui ~/NixOS
      - key: "2"
        desc: dotfiles
        cmd: kitty --app-id=repo --title=dotfiles -e jjui ~/dotfiles
      - key: "3"
        desc: dms
        cmd: kitty  --app-id repo --title=dms -e jjui ~/.config/quickshell/dms
      - key: "4"
        desc: niri
        cmd: kitty  --app-id repo --title=niri -e jjui ~/Code/niri
      - key: "5"
        desc: helix
        cmd: kitty  --app-id repo --title=helix -e jjui ~/Code/helix
      - key: "6"
        desc: jjui
        cmd: kitty  --app-id repo --title=jjui -e jjui ~/Code/jjui
      - key: "7"
        desc: nix-search-cli
        cmd: kitty  --app-id repo --title=nix-search-cli -e jjui ~/Code/nix-search-cli
      - key: "8"
        desc: dgop
        cmd: kitty  --app-id repo --title=dgop -e jjui ~/Code/dgop
      - key: "9"
        desc: dms-plugins
        cmd: kitty  --app-id repo --title=dms-plugins -e jjui ~/Code/dms-plugins
  - key: "l"
    desc: launch
    submenu:
        - key: "b"
          desc: "bOxbuddy, bTop"
          submenu:
            - key: "o"
              desc: "boxbuddy"
              cmd: boxbuddy-rs
            - key: "t"
              desc: btop
              cmd: kitty btop
        - key: "c"
          desc: calendar
          cmd: kitty khal interactive
        - key: "e"
          desc: emacs
          cmd: emacsclient -c
        - key: "f"
          desc: firefox
          cmd: firefox
        - key: "h"
          desc: helix
          cmd: kitty hx
        - key: "l"
          desc: lm-studio
          cmd: lm-studio 
        - key: "p"
          desc: podman-tui
          cmd: kitty podman-tui
        - key: "s"
          desc: spotify
          cmd: spotify --no-zygote
        - key: "y"
          desc: yazi
          cmd: kitty yazi ~/Downloads
  - key: "m"
    desc: music
    submenu:
      - key: "m"
        desc: mpd
        cmd: kitty rmpc
      - key: "s"
        desc: spotify
        cmd: kitty spotify_player
      - key: "v"
        desc: visualizer
        cmd: kitty cava
      - key: "a"
        desc: alsamixer
        cmd: kitty alsamixer
      - key: "p"
        desc: pipewire mixer
        submenu:
          - key: "g"
            desc: gui
            cmd: pwvucontrol
          - key: "t"
            desc: tui
            cmd: kitty ncpamixer
  - key: "n"
    desc: network
    cmd: kitty --app-id=nmtui nmtui
  - key: "t"
    desc: "timer"
    cmd: kitty --app-id=timer peaclock
