
bind=SUPER,KP_Enter,            spawn,dms ipc call spotlight toggle
bind=SUPER,P,                   spawn,dms ipc call dankdash wallpaper
bind=SUPER,c,                   spawn,dms ipc call clipboard toggle
bind=SUPER,a,                   spawn,dms ipc call notifications toggle
bind=SUPER,d,                   spawn,dms ipc call notifications dismissAllPopups
bind=SUPER,b,                   spawn,dms ipc call bar toggleAutoHide index 0
bind=SUPER,w,                   spawn,dms ipc call dash toggle weather
bind=SUPER,m,                   spawn,dms ipc call dash toggle media
bind=SUPER+SHIFT,n,             spawn,dms ipc call notepad toggle
bind=none,XF86AudioRaiseVolume, spawn,dms ipc call audio increment 1
bind=none,XF86AudioLowerVolume, spawn,dms ipc call audio decrement 1
bind=none,XF86AudioMute,        spawn,dms ipc call audio mute
bind=SUPER,q,                   spawn,dms ipc call powermenu toggle
bind=CTRL+ALT,Delete,           spawn,dms ipc call processlist toggle
bind=SUPER+SHIFT,t,             spawn,kitty set_timer
