#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title config-kitty
# @vicinae.mode silent

# kitty --detach hx -w ~/NixOS ~/NixOS/home/dot-config/kitty/kitty.conf
zellij run --cwd ~/NixOS -- hx ~/NixOS/home/dot-config/kitty/kitty.conf
