#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title config-nixos-flake
# @vicinae.mode silent

# kitty --detach hx -w ~/NixOS ~/NixOS/flake.nix
zellij run --cwd ~/NixOS -- hx ~/NixOS/flake.nix
