#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title Fish Configs
# @vicinae.mode silent

kitty --detach -d ~/NixOS/home/dot-config/fish -- hx config.fish conf.d/aliases-abbrs.fish
# zellij run --cwd ~/NixOS -- hx ~/NixOS/home/dot-config/fish/config.fish
