#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title config-niri-window-rules
# @vicinae.mode silent

# kitty --detach hx -w ~/NixOS ~/NixOS/home/dot-config/niri/window-rules.kdl
zellij run --cwd ~/NixOS -- hx ~/NixOS/home/dot-config/niri/window-rules.kdl
