#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title Mango Configs
# @vicinae.mode silent

zellij run --cwd ~/NixOS/home/dot-config/mango -- hx config.conf binds.conf rules.conf noctalia-binds.conf 
