#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title Yazi Configs
# @vicinae.mode silent

kitty --detach -d ~/NixOS/home/dot-config/yazi -- hx yazi.toml keymaps.toml
# zellij run --cwd ~/NixOS -- hx ~/NixOS/home/dot-config/yazi/yazi.toml
