#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title Helix Configs
# @vicinae.mode silent

kitty --detach -d ~/NixOS/home/dot-config/helix -- hx config.toml languages.toml
# zellij run --cwd ~/NixOS -- hx ~/NixOS/home/dot-config/helix/config.toml
