#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title Niri Configs
# @vicinae.mode silent

kitty --detach -d ~/NixOS/home/dot-config/niri -- nvim binds.kdl config.kdl spawns.kdl window-rules.kdl environment.kdl
