#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title config-yazi-main
# @vicinae.mode silent

# kitty --detach hx -w ~/NixOS ~/NixOS/home/dot-config/yazi/yazi.toml
zellij run --cwd ~/NixOS -- hx ~/NixOS/home/dot-config/yazi/yazi.toml
