#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title NixOS Configs
# @vicinae.mode silent

kitty --detach -d ~/NixOS -- hx modules/users.nix modules/programs.nix flake.nix home/home.nix modules/services.nix
# zellij run --cwd ~/NixOS -- hx ~/NixOS/modules/environment.nix
