#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title NixOS Configs
# @vicinae.mode silent

kitty --detach -d ~/NixOS -- nvim modules/users.nix modules/programs.nix flake.nix home/home.nix modules/services.nix
