#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title config-helix
# @vicinae.mode silent

# kitty --detach hx -w ~/NixOS ~/NixOS/home/dot-config/helix/config.toml
zellij run --cwd ~/NixOS -- hx ~/NixOS/home/dot-config/helix/config.toml
