#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title Update jjui
# @vicinae.mode silent

kitty --detach --app-id floater -- nix profile upgrade jjui
# zellij run -- nix profile upgrade jjui
