#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title Update DMS
# @vicinae.mode silent

# kitty --detach nix profile upgrade DankMaterialShell
zellij run -- nix profile upgrade DankMaterialShell
