#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title Update noctalia-shell
# @vicinae.mode silent

# kitty --detach nix profile upgrade noctalia-shell
zellij run -- nix profile upgrade noctalia-shell
