#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title Start Gemma4
# @vicinae.mode silent

pkill llama-server;llama-server -a 'Gemma4-E2B-Q5_K_M' -m ~/Code/models/gemma-4-E2B-it-Q5_K_M.gguf --ctx-size 16384 --temp 1.0 --top-p 0.95 --top-k 64 --jinja --reasoning off --port 8081 --host 127.0.0.1
