#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title Update Silverbullet
# @vicinae.mode silent

kitty --detach --app-id floater -- /home/kev/Code/podman/silverbullet/silverbullet-update-restart
