# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x040a09ff
rootcolor = 0x081512ff
bordercolor = 0x1e6d5aff
focuscolor = 0x1e9177ff
maximizescreencolor = 0x167a63ff
urgentcolor = 0x933636ff
scratchpadcolor = 0x26a589ff
globalcolor = 0x074537ff
overlaycolor = 0x064738ff
