
# General
bind=SUPER,b,					    spawn,noctalia-shell ipc call bar toggle
bind=SUPER,m,					    spawn,noctalia-shell ipc call media toggle
bind=SUPER,P,					    spawn,noctalia-shell ipc call wallpaper toggle
bind=SUPER,w,					    spawn,noctalia-shell ipc call calendar toggle
bind=SUPER,q,					    spawn,noctalia-shell ipc call sessionMenu toggle
bind=SUPER+SHIFT,m,					spawn,noctalia-shell ipc call systemMonitor toggle
bind=SUPER+SHIFT,n,					spawn,noctalia-shell ipc call plugin:notes-scratchpad togglePanel

# Launcher
bind=SUPER,c,			        	spawn,noctalia-shell ipc call launcher clipboard
bind=SUPER,e,			        	spawn,noctalia-shell ipc call launcher emoji
bind=SUPER,KP_Enter,				spawn,noctalia-shell ipc call launcher toggle

# Notifications
bind=SUPER,a,              			spawn,noctalia-shell ipc call notifications toggleHistory
bind=SUPER+Control+Shift,a,			spawn,noctalia-shell ipc call notifications clear
bind=SUPER+Shift,a,        			spawn,noctalia-shell ipc call notifications removeOldestHistory
bind=SUPER,d,              			spawn,noctalia-shell ipc call notifications dismissAll

# Timer
bind=SUPER,t,        				spawn,noctalia-shell ipc call plugin:timer toggle
bind=SUPER+Control,t,				spawn,noctalia-shell ipc call plugin:timer start stopwatch
bind=SUPER+Shift,t,  				spawn,noctalia-shell ipc call plugin:timer reset

# Media
bind=none,XF86AudioLowerVolume,		spawn,noctalia-shell ipc call volume decrease
bind=none,XF86AudioMute,       		spawn,noctalia-shell ipc call volume muteOutput
bind=none,XF86AudioRaiseVolume,		spawn,noctalia-shell ipc call volume increase

# Sticky Notes
bind=HYPER,n,        				spawn,noctalia-shell ipc call plugin:sticky-notes toggle
