
# General
bind=SUPER,b,                     spawn,noctalia msg bar-toggle
bind=SUPER,m,                     spawn,noctalia msg panel-toggle control-center media
bind=SUPER,P,                     spawn,noctalia msg panel-toggle launcher /wall
bind=SUPER+Shift,P,               spawn,noctalia msg wallpaper-set color:#15212f
bind=SUPER,w,                     spawn,noctalia msg panel-toggle control-center weather 
bind=SUPER+SHIFT,w,               spawn,noctalia msg panel-toggle calendar
bind=SUPER,q,                     spawn,noctalia msg panel-toggle session
bind=SUPER,period,                spawn,noctalia msg settings-toggle
bind=SUPER+SHIFT,m,               spawn,noctalia msg panel-toggle control-center system
bind=SUPER+SHIFT,n,               spawn,noctalia msg panel-toggle noctalia/notes:panel
bind=SUPER,c,                     spawn,noctalia msg panel-toggle clipboard
bind=SUPER,u,                     spawn,noctalia msg panel-toggle avivbintangaringga/nix-monitor:panel
bind=SUPER+SHIFT,c,               spawn,noctalia msg clipboard-clear
bind=SUPER+SHIFT,t,               spawn,noctalia msg theme-mode-toggle

# Launcher
# bind=SUPER,e,                     spawn,noctalia msg panel-toggle launcher /emo 
bind=SUPER,KP_Enter,              spawn,noctalia msg panel-toggle launcher

# Notifications
bind=SUPER,a,                     spawn,noctalia msg panel-toggle control-center notifications
# bind=SUPER+Control+Shift,a,       spawn,noctalia msg notifications clear
bind=SUPER+SHIFT,a,               spawn,noctalia msg notification-clear-history
bind=SUPER,d,                     spawn,noctalia msg notification-clear-active

# Timer
bind=SUPER,t,                     spawn,kitty clock-rs stopwatch

# Media
bind=none,XF86AudioLowerVolume,   spawn,noctalia msg volume-down 1
bind=none,XF86AudioMute,          spawn,noctalia msg volume-mute
bind=none,XF86AudioRaiseVolume,   spawn,noctalia msg volume-up 1
